"""patient summary: follow_up_date + reminder_logs

Revision ID: 4778ad4cf3af
Revises: 94a6140ff1ff
Create Date: 2026-09-26 12:18:41.191333
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4778ad4cf3af'
down_revision: Union[str, None] = '94a6140ff1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_logs_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_reminder_logs_patient_sent', ['patient_id', 'sent_at'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_up_date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('follow_up_date')

    with op.batch_alter_table('reminder_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_logs_patient_sent')
        batch_op.drop_index(batch_op.f('ix_reminder_logs_patient_id'))

    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
