"""initial schema

Revision ID: 94a6140ff1ff
Revises: 
Create Date: 2026-09-26 12:05:35.027610
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '94a6140ff1ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salt_a', sa.String(), nullable=True),
    sa.Column('salt_b', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_salt_a'), ['salt_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_interactions_salt_b'), ['salt_b'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=True)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('raw_ocr', sa.String(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('prescriber_name', sa.String(), nullable=True),
    sa.Column('prescriber_specialty', sa.String(), nullable=True),
    sa.Column('prescription_date', sa.String(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_patient_created', ['patient_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_thread_id'), ['thread_id'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('dosage_notation', sa.String(), nullable=True),
    sa.Column('timing', sa.JSON(), nullable=True),
    sa.Column('per_day', sa.Float(), nullable=True),
    sa.Column('prn', sa.Boolean(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_salt_confirmation', sa.Boolean(), nullable=True),
    sa.Column('prescriber_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_medicines_patient_status', ['patient_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_report_id'))
        batch_op.drop_index('ix_medicines_patient_status')
        batch_op.drop_index(batch_op.f('ix_medicines_patient_id'))

    op.drop_table('medicines')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_thread_id'))
        batch_op.drop_index(batch_op.f('ix_reports_patient_id'))
        batch_op.drop_index('ix_reports_patient_created')

    op.drop_table('reports')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))

    op.drop_table('patients')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_salt_b'))
        batch_op.drop_index(batch_op.f('ix_interactions_salt_a'))

    op.drop_table('interactions')
    # ### end Alembic commands ###
